name: de_by_stmd
title: Bayerisches Staatsministerium für Digitales
description: >
  Documents scraped from the public website of Bayerisches Staatsministerium für Digitales (www.stmd.bayern.de/)
country: de
category: library
coverage:
  frequency: daily
publisher:
  name: Bayerisches Staatsministerium für Digitales
  country: de
  url: https://www.stmd.bayern.de/
maintainer:
  name: "||)·|()"
  url: https://investigativedata.io
content_type: documents

stealthy: true

pipeline:
  init:
    method: utils.operations:init
    handle:
      pass: seed

  seed:
    method: seed
    params:
      url: https://www.stmd.bayern.de/
    handle:
      pass: fetch

  cached_emit:
    method: utils.operations:cached_emit
    handle:
      pass: fetch

  fetch:
    method: fetch
    params:
      rules:
        and:
          - or:
              - pattern: https://www.stmd.bayern.de/.*
              - pattern: https://stmd.bayern.de/.*
          - not:
              or:
                - mime_group: assets
                - mime_group: images
    handle:
      pass: parse

  parse:
    method: parse
    params:
      store:
        or:
          - mime_group: archives
          - mime_group: documents
          - mime_group: media
    handle:
      store: store
      fetch: cached_emit

  store:
    method: utils.operations:store
