name: de_sn_smwk
title: Sächsisches Staatsministerium für Wissenschaft, Kultur und Tourismus
description: >
  Documents scraped from the public website of Sächsisches Staatsministerium für Wissenschaft, Kultur und Tourismus (www.smwk.sachsen.de)
country: de
category: library
coverage:
  frequency: daily
publisher:
  name: Sächsisches Staatsministerium für Wissenschaft, Kultur und Tourismus
  country: de
  url: https://www.smwk.sachsen.de
maintainer:
  name: "||)·|()"
  url: https://investigativedata.io
content_type: documents

stealthy: true

pipeline:
  init:
    method: utils.operations:init
    handle:
      pass: seed

  seed:
    method: seed
    params:
      url: https://www.smwk.sachsen.de
    handle:
      pass: fetch

  cached_emit:
    method: utils.operations:cached_emit
    handle:
      pass: fetch

  fetch:
    method: fetch
    params:
      rules:
        and:
          - or:
              - pattern: https://www.smwk.sachsen.de.*
              - pattern: https://smwk.sachsen.de.*
          - not:
              or:
                - mime_group: assets
                - mime_group: images
    handle:
      pass: parse

  parse:
    method: parse
    params:
      store:
        or:
          - mime_group: archives
          - mime_group: documents
          - mime_group: media
    handle:
      store: store
      fetch: cached_emit

  store:
    method: utils.operations:store
