name: eu_fts
title: EU Financial Transparency System
country: eu

summary: |
  Beneficiaries of funding from the EU budget implemented directly by the
  Commission (at Headquarters or in EU delegations to non-EU countries) and
  other EU bodies such as executive agencies ('direct management') or
  implemented indirectly by other international organisations or non-EU
  countries ('indirect management'), and beneficiaries of the European
  Development Fund.

data_url: https://data.europa.eu/data/datasets/fts?locale=en

category: procurement
tags:
  - financial transparency
  - public funding
  - investigraph.eu

publisher:
  name: European Commission
  url: http://ec.europa.eu/budget/fts/index_en.htm

maintainer:
  name: DARC
  url: https://dataresearchcenter.org
  logo_url: https://cdn.investigativedata.org/style/logos/darc/svg/DARC-Logo-RGB-Horizontal-Neg.svg
git_repo: https://github.com/dataresearchcenter/datasets

extract:
  sources:
    - uri: https://ec.europa.eu/budget/financial-transparency-system/download/2024_FTS_dataset_en.xlsx
    - uri: https://ec.europa.eu/budget/financial-transparency-system/download/2023_FTS_dataset_en.xlsx
    - uri: https://ec.europa.eu/budget/financial-transparency-system/download/2022_FTS_dataset_en.xlsx
    - uri: https://ec.europa.eu/budget/financial-transparency-system/download/2021_FTS_dataset_en.xlsx
    - uri: https://ec.europa.eu/budget/financial-transparency-system/download/2020_FTS_dataset_en.xlsx
    - uri: https://ec.europa.eu/budget/financial-transparency-system/download/2019_FTS_dataset_en.xlsx
    - uri: https://ec.europa.eu/budget/financial-transparency-system/download/2018_FTS_dataset_en.xlsx
    - uri: https://ec.europa.eu/budget/financial-transparency-system/download/2017_FTS_dataset_en.xlsx
    - uri: https://ec.europa.eu/budget/financial-transparency-system/download/2016_FTS_dataset_en.xlsx
    - uri: https://ec.europa.eu/budget/financial-transparency-system/download/2015_FTS_dataset_en.xlsx
    - uri: https://ec.europa.eu/budget/financial-transparency-system/download/2014_FTS_dataset_en.xlsx
    - uri: https://ec.europa.eu/budget/financial-transparency-system/download/2013_FTS_dataset_en.xlsx
    - uri: https://ec.europa.eu/budget/financial-transparency-system/download/2012_FTS_dataset_en.xlsx
    - uri: https://ec.europa.eu/budget/financial-transparency-system/download/2011_FTS_dataset_en.xlsx
    - uri: https://ec.europa.eu/budget/financial-transparency-system/download/2010_FTS_dataset_en.xlsx
    - uri: https://ec.europa.eu/budget/financial-transparency-system/download/2009_FTS_dataset_en.xlsx
    - uri: https://ec.europa.eu/budget/financial-transparency-system/download/2008_FTS_dataset_en.xlsx
    - uri: https://ec.europa.eu/budget/financial-transparency-system/download/2007_FTS_dataset_en.xlsx
  pandas:
    read:
      options:
        dtype: str
    operations:
      - handler: DataFrame.fillna
        options:
          value: ""
      - handler: DataFrame.rename
        options:
          columns:
            "Year": date
            "Reference (Budget)": payment_recordId
            "Name of beneficiary": beneficiary_name
            "VAT number of beneficiary": beneficiary_vatCode
            "Coordinator": beneficiary_role
            "Address": beneficiary_street
            "City": beneficiary_city
            "Postal code": beneficiary_postcode
            "Beneficiary country": beneficiary_country
            "Beneficiary’s contracted amount (EUR)": payment_amount
            "Subject of grant or contract": project_identifier
            "Budget line name": project_name
            "Programme name": program
            "Beneficiary type": beneficiary_type
            "Project start date": project_startDate
            "Project end date": project_endDate
            "Responsible department": payer

transform:
  handler: ./transform.py:handle
