name: de_bw_fm
title: Ministerium für Finanzen Baden-Württemberg
description: >
  Documents scraped from the public website of Ministerium für Finanzen Baden-Württemberg (fm.baden-wuerttemberg.de)
country: de
category: library
coverage:
  frequency: daily
publisher:
  name: Ministerium für Finanzen Baden-Württemberg
  country: de
  url: https://fm.baden-wuerttemberg.de
maintainer:
  name: "||)·|()"
  url: https://investigativedata.io
content_type: documents

stealthy: true

pipeline:
  init:
    method: utils.operations:init
    handle:
      pass: seed

  seed:
    method: seed
    params:
      url: https://fm.baden-wuerttemberg.de
    handle:
      pass: fetch

  cached_emit:
    method: utils.operations:cached_emit
    handle:
      pass: fetch

  fetch:
    method: fetch
    params:
      rules:
        and:
          - or:
              - pattern: https://fm.baden-wuerttemberg.de.*
              - pattern: https://fm.baden-wuerttemberg.de.*
          - not:
              or:
                - mime_group: assets
                - mime_group: images
    handle:
      pass: parse

  parse:
    method: parse
    params:
      store:
        or:
          - mime_group: archives
          - mime_group: documents
          - mime_group: media
    handle:
      store: store
      fetch: cached_emit

  store:
    method: utils.operations:store
