name: eu-stateaid
title: State Aid Transparency Public Search
publisher:
  name: European Commission
  url: https://webgate.ec.europa.eu/competition/transparency/public
maintainer:
  name: DARC
  url: https://dataresearchcenter.org
  logo_url: https://cdn.investigativedata.org/style/logos/darc/svg/DARC-Logo-RGB-Horizontal-Neg.svg
git_repo: https://github.com/dataresearchcenter/datasets

resources:
  - name: entities.ftm.json
    url: https://data.ftm.store/eu_stateaid/entities.ftm.json
    mime_type: application/json+ftm

extract:
  sources:
    - uri: ./20240208-eu-stateaid.csv.gz
      pandas:
        read:
          options:
            compression: gzip
            dtype: str
        operations:
          - handler: DataFrame.rename
            options:
              columns:
                "20240208-eu-stateaid.csv": Country

transform:
  queries:
    - entities:
        payer:
          schema: PublicBody
          key_literal: eu-stateaid-authority
          keys:
            - Country
            - Granting Authority Name
            - Granting Authority Name [EN]
          properties:
            country:
              column: Country
            name:
              columns:
                - Granting Authority Name
                - Granting Authority Name [EN]
        beneficiary:
          schema: LegalEntity
          key_literal: eu-stateaid-beneficiary
          keys:
            - "National ID"
          properties:
            name:
              columns:
                - "Name of the beneficiary"
                - "Name of the beneficiary [EN]"
            sector:
              column: "Sector (NACE)"
            country:
              column: "Another Beneficiary Member State"
        payment:
          schema: Payment
          key_literal: eu-stateaid-payment
          keys:
            - "Ref-no."
          properties:
            transactionNumber:
              column: "Ref-no."
            programme:
              columns:
                - "Aid Instrument"
                - "Aid Instrument [EN]"
            purpose:
              columns:
                - "Objectives of the Aid"
                - "Objectives of the Aid [EN]"
            summary:
              columns:
                - "Aid Measure Title"
                - "Aid Measure Title [EN]"
            date:
              column: "Date of granting"
              format: "%d/%m/%Y"
            beneficiary:
              entity: beneficiary
            payer:
              entity: payer
            currency:
              column: "Currency"
            amount:
              columns:
                - "Nominal Amount, expressed as full amount"
                - "Aid element, expressed as full amount"
