name: de_nw_mbei
title: Minister für Bundes- und Europaangelegenheiten, Internationales sowie Medien des Landes Nordrhein-Westfalen
description: >
  Documents scraped from the public website of Minister für Bundes- und Europaangelegenheiten, Internationales sowie Medien des Landes Nordrhein-Westfalen (www.mbei.nrw)
country: de
category: library
coverage:
  frequency: daily
publisher:
  name: Minister für Bundes- und Europaangelegenheiten, Internationales sowie Medien des Landes Nordrhein-Westfalen
  country: de
  url: https://www.mbei.nrw
maintainer:
  name: "||)·|()"
  url: https://investigativedata.io
content_type: documents

stealthy: true

pipeline:
  init:
    method: utils.operations:init
    handle:
      pass: seed

  seed:
    method: seed
    params:
      url: https://www.mbei.nrw
    handle:
      pass: fetch

  cached_emit:
    method: utils.operations:cached_emit
    handle:
      pass: fetch

  fetch:
    method: fetch
    params:
      rules:
        and:
          - or:
              - pattern: https://www.mbei.nrw.*
              - pattern: https://mbei.nrw.*
          - not:
              or:
                - mime_group: assets
                - mime_group: images
    handle:
      pass: parse

  parse:
    method: parse
    params:
      store:
        or:
          - mime_group: archives
          - mime_group: documents
          - mime_group: media
    handle:
      store: store
      fetch: cached_emit

  store:
    method: utils.operations:store
