name: de_bgh
title: Entscheidungen des Bundesgerichtshof (BGH)
description: >
  Scraped documents from the court archive of the german "Bundesgerichtshof
  (BGH)"
category: court
publisher:
  name: Bundesgerichtshof
  url: https://www.bundesgerichtshof.de
  official: true
  country: de
  description: >
    Der Bundesgerichtshof (BGH) ist das oberste Gericht der Bundesrepublik
    Deutschland im Bereich der Zivil- und Strafrechtspflege, der sogenannten
    ordentlichen Gerichtsbarkeit. Er wurde am 1. Oktober 1950 errichtet und hat
    seinen Sitz in Karlsruhe.
maintainer:
  name: "||)·|()"
  url: https://investigativedata.io
coverage:
  frequency: daily
content_type: documents
data_url: https://www.bundesgerichtshof.de/SiteGlobals/Forms/Suche/EntscheidungssucheBGH_Formular.html

pipeline:
  init:
    method: ./operations.py:seed
    params:
      url: https://www.bundesgerichtshof.de/SiteGlobals/Forms/Suche/EntscheidungssucheBGH_Formular.html
      days: 30
    handle:
      pass: fetch

  fetch:
    method: fetch
    handle:
      pass: parse

  parse:
    method: ./operations.py:parse
    handle:
      download: download
      fetch: fetch

  download:
    method: fetch
    handle:
      pass: store

  store:
    method: lakehouse
    params:
      compute_path:
        method: template
        params:
          template: "{{ department }}/{{ date[:4] }}/{{ date[5:7] }}/{{ reference.replace('/','-') }}.pdf"
