name: de_bgh
title: Entscheidungen des Bundesgerichtshof (BGH)
description: >
  Scraped documents from the court archive of the german "Bundesgerichtshof
  (BGH)"
category: court
publisher:
  name: Bundesgerichtshof
  url: https://www.bundesgerichtshof.de
  official: true
  country: de
  description: >
    Der Bundesgerichtshof (BGH) ist das oberste Gericht der Bundesrepublik
    Deutschland im Bereich der Zivil- und Strafrechtspflege, der sogenannten
    ordentlichen Gerichtsbarkeit. Er wurde am 1. Oktober 1950 errichtet und hat
    seinen Sitz in Karlsruhe.
maintainer:
  name: "||)·|()"
  url: https://investigativedata.io
coverage:
  frequency: daily
content_type: documents
data_url: https://juris.bundesgerichtshof.de/cgi-bin/rechtsprechung/list.py?Gericht=bgh&Art=en
aleph_url: https://aleph.investigativedata.org/datasets/581

pipeline:
  init:
    method: session
    params:
      proxy: http://archivebox1:8080
    handle:
      pass: dates

  dates:
    # method: dates
    method: de_bgh:dates
    params:
      format: "%Y-%m"
      end: 2000-01
      days: 30
    handle:
      pass: seed

  seed:
    method: seed
    params:
      url: https://juris.bundesgerichtshof.de/cgi-bin/rechtsprechung/list.py?Gericht=bgh&Art=en&Datum=%(date)s
    handle:
      pass: fetch

  fetch:
    method: fetch
    handle:
      pass: parse

  parse:
    method: de_bgh:parse
    handle:
      download: download
      fetch: fetch

  download:
    method: fetch
    handle:
      pass: store

  store:
    method: directory

leakrfc:
  sync:
    memorious:
      key_template: "{{ department }}/{{ date[:4] }}/{{ date[5:7] }}/{{ reference.replace('/','-') }}.pdf"
