name: eu_ceo_documents
description: Documents and reports published on the Corporate Europe Observatory website

pipeline:
  init:
    method: utils.operations:init
    handle:
      pass: seed

  seed:
    method: seed
    params:
      url: https://corporateeurope.org
    handle:
      pass: fetch

  fetch:
    method: fetch
    params:
      rules:
        and:
          - domain: https://corporateeurope.org
          - not:
              or:
                - mime_group: assets
                - mime_group: images
    handle:
      pass: cached_emit

  cached_emit:
    method: utils.operations:cached_emit
    handle:
      pass: parse

  parse:
    method: parse
    params:
      store:
        or:
          - mime_group: archives
          - mime_group: documents
    handle:
      store: store
      fetch: fetch

  store:
    method: utils.operations:store
