name: ocds_all

on:
  workflow_dispatch: {}

jobs:
  data:
    runs-on: ubuntu-latest
    container: ghcr.io/dataresearchcenter/datasets:latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      FSSPEC_S3_ENDPOINT_URL: ${{ secrets.FSSPEC_S3_ENDPOINT_URL }}
    strategy:
      fail-fast: false
      matrix:
        dataset:
          # Daily
          - ar_ocds_dnv
          - au_ocds_nsw
          - br_ocds_seges
          - ca_ocds_montreal
          - cl_ocds_chilecompra_api
          - cl_ocds_chilecompra_hist
          - co_ocds_ancp
          - de_ocds_bmi
          - do_ocds_dgcp
          - ec_ocds_sercop
          - fr_ocds_dinum
          - gb_ocds_contracts_finder
          - gb_ocds_find_a_tender_service
          - gb_ocds_sell2wales
          - gb_ocds_spcd
          - gt_ocds_minfin
          - hn_ocds_oncae
          - it_ocds_mit
          - ke_ocds_ppra
          - md_ocds_ministry_of_finance
          - pa_ocds_dgcp
          - pe_ocds_oece
          - pe_ocds_peru_compras
          - py_ocds_dncp
          - py_ocds_ministerio_de_hacienda
          - rw_ocds_rppa
          - tz_ocds_ppra
          - uy_ocds_arce_api
          # Weekly
          - es_ocds_spain
          - lt_ocds_lithuania
          - mx_ocds_secadmin_nuevo_leon
          - ro_ocds_romania
          - us_ocds_portland
          # Monthly
          - ar_ocds_dgcc
          - ar_ocds_dgcgb
          - br_ocds_medicamentos_transparentes
          - ca_ocds_quebec_sct
          - gh_ocds_ppa
          - hr_ocds_narodne_navine_dd
          - it_ocds_italy
          - mx_ocds_inai
          - nl_ocds_minezk
          - ug_ocds_ppda
          - zm_ocds_zppa
          # Annually
          - at_ocds_austria
          - be_ocds_belgium
          - bg_ocds_bulgaria
          - bo_ocds_agetic
          - ch_ocds_switzerland
          - cy_ocds_cyprus
          - cz_ocds_czechia
          - de_ocds_germany
          - dk_ocds_denmark
          - ee_ocds_estonia
          - eu_ocds_institutions
          - fi_ocds_finland
          - fr_ocds_france
          - gb_ocds_uk
          - ge_ocds_georgia
          - gr_ocds_greece
          - hr_ocds_croatia
          - hu_ocds_hungary
          - ie_ocds_ireland
          - in_ocds_assam
          - is_ocds_iceland
          - lu_ocds_luxembourg
          - lv_ocds_latvia
          - mk_ocds_northmacedonia
          - mt_ocds_malta
          - mx_ocds_sea_aguascalientes
          - nl_ocds_netherlands
          - no_ocds_norway
          - pl_ocds_poland
          - pt_ocds_portugal
          - rs_ocds_serbia
          - se_ocds_sweden
          - si_ocds_slovenia
          - sk_ocds_slovakia
          - uy_ocds_arce_hist
          # Unknown frequency
          - al_ocds_ppc
          - au_ocds_austender
          - cr_ocds_poder_judicial
          - es_ocds_zaragoza
          - hn_ocds_iaip
          - hn_ocds_sefin
          - id_ocds_icw
          - it_ocds_anac
          - lr_ocds_ppcc
          - mx_ocds_iaip_guanajuato
          - mx_ocds_idaip_durango
          - mx_ocds_inaip_yucatan
          - mx_ocds_infocdmx
          - mx_ocds_semov_nuevo_leon
          - ng_ocds_anambra
          - ng_ocds_bpp
          - ng_ocds_budeshi
          - ng_ocds_ebonyi
          - ng_ocds_ekiti
          - ng_ocds_osun
          - ng_ocds_plateau
          - np_ocds_dhangadhi
          - si_ocds_mju
          - xk_ocds_pprc
          - za_ocds_national_treasury
          # Never (no longer updated - historical data)
          - ua_ocds_prozorro
          - ca_ocds_buyandsell
          - co_ocds_ani
          - ge_ocds_state_procurement_agency
          - hn_ocds_sisocs
          - in_ocds_himachalpradesh
          - it_ocds_ondata
          - ke_ocds_makueni
          - kg_ocds_mof_ppd
          - mx_ocds_ceaip_sinaloa
          - mx_ocds_cotai_nuevo_leon
          - mx_ocds_guadalajara
          - mx_ocds_iaip_oaxaca
          - mx_ocds_iaip_quintana_roo
          - mx_ocds_infoem
          - mx_ocds_itaip_puebla
          - mx_ocds_ivai
          - mx_ocds_izai
          - mx_ocds_quienesquien
          - ng_ocds_abia
          - ng_ocds_crossriver
          - ng_ocds_edo
          - ng_ocds_enugu
          - ng_ocds_gombe
          - ng_ocds_oyo
          - np_ocds_ppmo
          - pt_ocds_impic
    steps:
      - name: parse and write the dataset
        run: make investigraph dataset=${{ matrix.dataset }} DATASETS_DIR=.
        working-directory: /datasets

  catalog:
    needs: data
    if: always()
    runs-on: ubuntu-latest
    container: ghcr.io/dataresearchcenter/datasets:latest
    defaults:
      run:
        working-directory: /datasets
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      FSSPEC_S3_ENDPOINT_URL: ${{ secrets.FSSPEC_S3_ENDPOINT_URL }}
    steps:
      - name: Update the catalog
        run: "make publish"
