name: gb_ocod
title: Overseas companies that own property in England and Wales
country: gb
summary: |
  The data shows every completed record about non-UK Companies or corporate bodies
  that own land in England and Wales.

  The data does not show land or property owned by:
  - private individuals
  - UK companies with an overseas address
  - charities
publisher:
  name: HM Land Registry
  description: |
    His Majesty's Land Registry is a non-ministerial department of His Majesty's Government,
    created in 1862 to register the ownership of land and property in England and Wales.
  url: https://use-land-property-data.service.gov.uk/datasets/ocod
resources:
  - name: entities.ftm.json
    url: https://data.ftm.store/gb_ocod/entities.ftm.json
    mime_type: application/json+ftm
git_repo: https://github.com/dataresearchcenter/datasets
maintainer:
  name: DARC
  url: https://dataresearchcenter.org
  logo_url: https://cdn.investigativedata.org/style/logos/darc/svg/DARC-Logo-RGB-Horizontal-Neg.svg

extract:
  sources:
    - uri: https://use-land-property-data.service.gov.uk/api/v1/datasets/ocod
  handler: ./extract.py:handle

transform:
  queries:
    - entities:
        company1:
          schema: Company
          keys:
            - "Proprietor Name (1)"
            - "Company Registration No. (1)"
          properties:
            name:
              column: "Proprietor Name (1)"
            registrationNumber:
              column: "Company Registration No. (1)"
            legalForm:
              column: "Proprietorship Category (1)"
            country:
              column: "Country Incorporated (1)"
            address:
              columns:
                - "Proprietor (1) Address (1)"
                - "Proprietor (1) Address (2)"
                - "Proprietor (1) Address (3)"
        company2:
          schema: Company
          keys:
            - "Proprietor Name (2)"
            - "Company Registration No. (2)"
          properties:
            name:
              column: "Proprietor Name (2)"
            registrationNumber:
              column: "Company Registration No. (2)"
            legalForm:
              column: "Proprietorship Category (2)"
            country:
              column: "Country Incorporated (2)"
            address:
              columns:
                - "Proprietor (1) Address (1)"
                - "Proprietor (1) Address (2)"
                - "Proprietor (1) Address (3)"
        company3:
          schema: Company
          keys:
            - "Proprietor Name (3)"
            - "Company Registration No. (3)"
          properties:
            name:
              column: "Proprietor Name (3)"
            registrationNumber:
              column: "Company Registration No. (3)"
            legalForm:
              column: "Proprietorship Category (3)"
            country:
              column: "Country Incorporated (3)"
            address:
              columns:
                - "Proprietor (1) Address (1)"
                - "Proprietor (1) Address (2)"
                - "Proprietor (1) Address (3)"
        company4:
          schema: Company
          keys:
            - "Proprietor Name (4)"
            - "Company Registration No. (4)"
          properties:
            name:
              column: "Proprietor Name (4)"
            registrationNumber:
              column: "Company Registration No. (4)"
            legalForm:
              column: "Proprietorship Category (4)"
            country:
              column: "Country Incorporated (4)"
            address:
              columns:
                - "Proprietor (1) Address (1)"
                - "Proprietor (1) Address (2)"
                - "Proprietor (1) Address (3)"
        address:
          schema: Address
          keys:
            - "Property Address"
            - "District"
            - "County"
            - "Region"
            - "Postcode"
          properties:
            full:
              column: "Property Address"
              literal: "UK"
              join: ", "
            country:
              literal: "United Kingdom"
            postalCode:
              column: "Postcode"
            region:
              column: "Region"
            state:
              column: "County"
            city:
              column: "District"
        real_estate:
          schema: RealEstate
          keys:
            - "Title Number"
          properties:
            addressEntity:
              entity: address
            registrationNumber:
              column: "Title Number"
            tenure:
              column: "Tenure"
            amount:
              column: "Price Paid"
        owner1:
          schema: Ownership
          key_literal: Ownership1
          keys:
            - "Proprietor Name (1)"
            - "Company Registration No. (1)"
            - "Title Number"
          properties:
            owner:
              entity: company1
              required: true
            asset:
              entity: real_estate
              required: true
            role:
              literal: "Proprietor"
        owner2:
          schema: Ownership
          key_literal: Ownership2
          keys:
            - "Proprietor Name (2)"
            - "Company Registration No. (2)"
            - "Title Number"
          properties:
            owner:
              entity: company2
              required: true
            asset:
              entity: real_estate
              required: true
            role:
              literal: "Proprietor"
        owner3:
          schema: Ownership
          key_literal: Ownership3
          keys:
            - "Proprietor Name (3)"
            - "Company Registration No. (3)"
            - "Title Number"
          properties:
            owner:
              entity: company3
              required: true
            asset:
              entity: real_estate
              required: true
            role:
              literal: "Proprietor"
        owner4:
          schema: Ownership
          key_literal: Ownership4
          keys:
            - "Proprietor Name (4)"
            - "Company Registration No. (4)"
            - "Title Number"
          properties:
            owner:
              entity: company4
              required: true
            asset:
              entity: real_estate
              required: true
            role:
              literal: "Proprietor"
